name: Actions
on: [push, workflow_dispatch]
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: retail-store-app-ui
  CONFIG_REPO_NAME: retail-config

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run installation of dependencies commands
        run: npm install -g snyk


  code-vulnerability-scanning:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Run vulernability scan
          run: |
            echo "To do"
            echo "Add scanning"
            snyk test
        
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
         distribution: 'temurin'
         java-version: '11'

  BUILD_AND_PUBLISH:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build & Upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
         access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
         secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         registry: ${{ secrets.REGISTRY }}
         repo: ${{ env.ECR_REPOSITORY }}
         region: ${{ env.AWS_REGION }}
         tags: latest,${{ github.sha }}
         daemon_off: false
         dockerfile: ./Dockerfile
         context: ./
  DEPLOY_TO_PROD:
    runs-on: ubuntu-latest
    needs: BUILD_AND_PUBLISH
    steps:
      - run: |
          echo "Deploying into Prod env!"
          git config --global user.email ci-bot-c5g4@test.com && git config --global user.name ci-bot-c5g4
          echo "cloning config repo $CONFIG_REPO_NAME"
          git clone https://oauth2:${{ secrets.PAT_GH }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO_NAME.git
          cd $CONFIG_REPO_NAME
          git checkout main
          sed -i "s,tag:.*,tag:\ ${{ github.sha }}," helm/retailapp/values.yaml
          git add . && git commit -m "update image tag"
          git push
